- name: "Instalação do NGNIX"
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: "Step 1: Aguardando o sistema ficar acessivel"
      wait_for_connection:
        timeout: 600
    - name: "Step 2: Aguardando o cloud-init ficar disponível"
      command: cloud-init status --wait
      changed_when: false
    - name: "Step 3: Instalando o NGNIX"
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
    - name: "Step 4: Iniciando o serviço do NGINX"
      ansible.builtin.service:
        name: nginx
        state: started
      tags: restart
